import Head from 'next/head'
import { useState } from 'react'
import CustomerReviewCard from './components/CustomerReviewCard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing page intro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <div className="flex flex-col h-screen justify-center items-center main-container">
        <CustomerReviewCard />
        <div className="attribution">
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>.
          Coded by <a href="https://www.frontendmentor.io/profile/duongbkak55">duongbkak55-Nguyễn Văn Dương</a>.
        </div>
      </div>

    </div>
  )
}
